"""Adding Answers and Queries

Revision ID: 157f616cecd3
Revises: 4e362fac6b82
Create Date: 2025-08-30 00:14:38.409301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157f616cecd3'
down_revision: Union[str, Sequence[str], None] = '4e362fac6b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('conversation_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'answers', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'conversation_id')
    # ### end Alembic commands ###
