"""Add URI to Document

Revision ID: 7493bc9b5906
Revises: 39f89cb8a3f1
Create Date: 2025-08-23 19:02:51.750978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7493bc9b5906'
down_revision: Union[str, Sequence[str], None] = '39f89cb8a3f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uri_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'uri_path')
    # ### end Alembic commands ###
