"""Title to Chunks

Revision ID: 8b9b761113cc
Revises: c207a0fdcf1c
Create Date: 2025-08-27 17:21:40.639328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9b761113cc'
down_revision: Union[str, Sequence[str], None] = 'c207a0fdcf1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'title')
    # ### end Alembic commands ###
