"""Adding Page number to chunk

Revision ID: c207a0fdcf1c
Revises: cb25413a637e
Create Date: 2025-08-26 23:09:08.144724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c207a0fdcf1c'
down_revision: Union[str, Sequence[str], None] = 'cb25413a637e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'page_number')
    # ### end Alembic commands ###
